# MPLAB IDE generated this makefile for use with GNU make.
# Project: PRACTICA3.mcp
# Date: Thu Sep 22 22:49:26 2022

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

PRACTICA3.cof : PRACTICA3.o
	$(CC) /p18F45K50 "PRACTICA3.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"PRACTICA3.cof" /M"PRACTICA3.map" /W

PRACTICA3.o : PRACTICA3.asm ../../../../../../../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/P18F45K50.inc
	$(AS) /q /p18F45K50 "PRACTICA3.asm" /l"PRACTICA3.lst" /e"PRACTICA3.err" /o"PRACTICA3.o" /d__DEBUG=1

clean : 
	$(CC) "PRACTICA3.o" "PRACTICA3.err" "PRACTICA3.lst" "PRACTICA3.cof" "PRACTICA3.hex"

