# MPLAB IDE generated this makefile for use with GNU make.
# Project: PRACTICA2.mcp
# Date: Wed Sep 14 22:27:41 2022

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

PRACTICA2.cof : PRACTICA2.o
	$(CC) /p18F45K50 "PRACTICA2.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"PRACTICA2.cof" /M"PRACTICA2.map" /W

PRACTICA2.o : PRACTICA2.asm ../../../../../../../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/P18F45K50.inc
	$(AS) /q /p18F45K50 "PRACTICA2.asm" /l"PRACTICA2.lst" /e"PRACTICA2.err" /o"PRACTICA2.o" /d__DEBUG=1

clean : 
	$(CC) "PRACTICA2.o" "PRACTICA2.err" "PRACTICA2.lst" "PRACTICA2.cof" "PRACTICA2.hex"

